### ISSUE TITLE
What should I do if the macOS host is infected by the test on the win7 virtual machine?

### ISSUE THREAD

**Issue by sethxiong** [ghidraninja/ReversingWannacry#2]
Using your 1831.bin to test in the win7 virtual machine, many files of the host macOS have also been modified, and the win7 virtual machine has been shut down. At present, restarting the virtual machine fails. Because the source file of the win7 virtual machine has also been modified, VMWare cannot start the win7 virtual machine. what should I do?

![1271625205926_ pic_hd](https://user-images.githubusercontent.com/43454145/124228271-9178cb00-db3e-11eb-9421-abb2ce843581.jpg)

**Comment by nezza** [comment]
Sounds like you somehow had mapped the OSX file-system into the VM? Nothing you can do really, I'd recommend setting up a new VM

**Comment by sethxiong** [comment]
I installed win7 in a seamless way a long time ago. Just a few hours ago, I used a link to clone a new win7 virtual machine, so the host was infected. Is there any way I can decrypt it now? Looking forward to your reply, thanks 🙏

![image](https://user-images.githubusercontent.com/43454145/124266186-39a38980-db69-11eb-91b9-053c30bff745.jpeg)

**Comment by sethxiong** [comment]
A lot of data on my host OSX has been infected, and I urgently need a decryption method to restore it.

![image](https://user-images.githubusercontent.com/43454145/124272069-d9184a80-db70-11eb-811b-909c6e502085.jpeg)

**Comment by nezza** [comment]
I don't think there currently is a decryption method, especially as the Windows drive got encrypted - I recommend restoring from backup
